language: python
python:
  - 3.5 # Toolforge bastion/grid
  - 3.6
  - 3.7 # Toolforge k8s
  - 3.8
  - nightly
  - pypy3
jobs:
  allow_failures:
  - python: nightly
  - python: pypy3
  fast_finish: true
os: linux
install:
  - pip install --upgrade pip setuptools wheel
  - python setup.py install
  - pip install pylint
script:
  - pylint bsiconsbot scripts
