language: python
python:
    - 3.4
    - 3.5
    - 3.6
sudo: false
os: linux
install:
    - pip install -U setuptools
    - python setup.py install
    - pip install pylint
script:
    - pylint scripts
